### PR TITLE
Fix inferred types error

### PR DESCRIPTION
**Pull request by glensc**
```
$ tsc
src/routes/index.ts:6:7 - error TS2742: The inferred type of 'router' cannot be named without a reference to
'.pnpm/@types+express-serve-static-core@4.17.39/node_modules/@types/express-serve-static-core'. This is likely not portable. A type annotation is necessary.

6 const router = Router();
        ~~~~~~

src/routes/probes.ts:5:7 - error TS2742: The inferred type of 'router' cannot be named without a reference to
'.pnpm/@types+express-serve-static-core@4.17.39/node_modules/@types/express-serve-static-core'. This is likely not portable. A type annotation is necessary.

5 const router = Router();
        ~~~~~~

src/services/httpServer.ts:6:7 - error TS2742: The inferred type of 'app' cannot be named without a reference to
'.pnpm/@types+express-serve-static-core@4.17.39/node_modules/@types/express-serve-static-core'. This is likely not portable. A type annotation is necessary.

6 const app = express();
        ~~~

Found 3 errors in 3 files.

Errors  Files
     1  src/routes/index.ts:6
     1  src/routes/probes.ts:5
     1  src/services/httpServer.ts:6
```

Broken from 47f81e02d20bd1cb61d52cc894ce5b1591f7c34f

### CODE REVIEW

**Comment by glensc** [comment]
Not something obvious seen why:
- https://github.com/DefinitelyTyped/DefinitelyTyped/commits/6a22bde81efbe00c087bc26763cd7a7927ff7933/types/express-serve-static-core

**Comment by glensc** [comment]
maybe this:
- https://github.com/microsoft/TypeScript/issues/42873
